### PR TITLE
Lps 88984b

### PR DESCRIPTION
**Pull request by SpencerWoo**
from https://github.com/SpencerWoo/liferay-portal/pull/43

@jrao 
let me know if this looks okay

### CODE REVIEW

**Comment by SpencerWoo** [comment]
ci:test:relevant

**Comment by SpencerWoo** [comment]
ci:test:sf

**Comment by jrao** [comment]
@SpencerWoo The refactor looks good to me. But the use different listeners commit looks like an approach I tried during development that didn't pan out.

When I deploy that update, I get these kind of JS errors:

```Uncaught TypeError: Cannot read property 'dropContainer' of null
    at Object.getActiveDropNodes (:8080/combo/?browser...feray/layout.js:733)```

**Comment by SpencerWoo** [comment]
@jrao 
I don't get that error, or any error.  When you revert the last commit then there's no errors?

**Comment by jrao** [comment]
Just started reviewing :)

**Comment by jrao** [comment]
Just started reviewing :)

**Comment by jrao** [comment]
Whether I have just your first commit or both of your commits, I still get the error. But it occurs intermittently - sometimes it does not occur. But resizing doesn't work correctly without a page refresh (regardless of whether I have just your first or both of your commits applied).

**Comment by SpencerWoo** [comment]
https://github.com/jrao/liferay-portal/pull/41

**Pull request closed without merging**
