### PR TITLE
LPS-70547 Allow httpclient-osgi v4 to be used in modules

### PR DESCRIPTION
**Pull request by jrao**
LPS-70547 Allow httpclient-osgi v4 to be used in modules

### CODE REVIEW

**Comment by jrao** [comment]
ci:test

**Comment by jrao** [comment]
ci:retest

**Comment by jrao** [comment]
ci:retest

**Comment by rotty3000** [comment]
Hey @jrao  this needs to be rebased and sent to me again.

**Comment by jrao** [comment]
@rotty3000 Ok, just rebased. But test is still failing due to another issue.

**Pull request closed without merging**
